apiVersion: apps/v1
kind: Deployment
metadata:
  name: springrestapi-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: springrestapi
  template:
    metadata:
      labels:
        app: springrestapi
    spec:
      containers:
      - name: springrestapi-container
        image: priya123456/springrestapi:45
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: springrestapi-service
spec:
  type: NodePort
  selector:
    app: springrestapi
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30371
    
